package server.authentication.exceptions.user

class UserExistsException : UserException("User already exists")